steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/cr-api-generate-pdf:$COMMIT_SHA', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/cr-api-generate-pdf:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'cr-api-generate-pdf', '--image', 'gcr.io/${PROJECT_ID}/cr-api-generate-pdf:$COMMIT_SHA', '--region', 'us-central1', '--allow-unauthenticated']
images:
- gcr.io/${PROJECT_ID}/cr-api-generate-pdf:$COMMIT_SHA

